#!/bin/sh /etc/rc.common
# Copyright (C) 2016 OpenWrt.org

START=70

start() {
	/usr/sbin/nrpe -c /etc/nrpe.cfg -d
}

stop() {
	killall nrpe
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	killall -1 nrpe
}
